### PR TITLE
(feat) finish refactor and also add description of goal to progress page

### PR DESCRIPTION
**Pull request by david-hammer**

### CODE REVIEW

**Comment by lpww** [comment]
Cool changes!

**Comment by yesplease** [comment]
:o: :ocean: :octopus:  :octocat:

**Comment by yesplease** [comment]
WTF

**Comment by yesplease** [comment]
THOMAS!

**Comment by yesplease** [comment]
@lpww woooow

**Comment by david-hammer** [comment]
@lpww where u at

**Comment by yesplease** [comment]
@Sourdoughh do you think @lpww acted within bounds?

**Comment by yesplease** [comment]
@david-hammer great code. here's an ocotcat. :octocat:

**Comment by david-hammer** [comment]
Let's elevate this issue straight to the top: @Sunyang730

**Comment by jasonly** [comment]
:100: !

**Pull request merged**
